//
//  main.m
//  generate-string-symbols
//
//  Created by Daniel Kennett on 07/08/14.
//  For license information, see LICENSE.markdown

#import <Foundation/Foundation.h>

#pragma mark - Usage

void printUsage() {

    NSString *processName = [[NSProcessInfo processInfo] processName];
    NSString *processNamePadding = [@"" stringByPaddingToLength:processName.length
                                                     withString:@" "
                                                startingAtIndex:0];

    printf("%s by Daniel Kennett\n\n", processName.UTF8String);

    printf("Outputs a header file containing symbols for the given .strings\n");
    printf("file's keys.\n\n");

    printf("Usage: %s -strings <strings file path>\n", processName.UTF8String);
    printf("       %s -out <output file path> \n", processNamePadding.UTF8String);
    printf("       %s -skipwriteifunchanged <YES/NO> \n\n", processNamePadding.UTF8String);

    printf("  -strings  The path to a valid .strings file.\n\n");

    printf("  -out      The path to write the output header file to. Missing\n");
    printf("            directories will be created along the way. If a file\n");
    printf("            already exists at the given path, it will be\n");
    printf("            overwritten.\n\n");

    printf("  -skipwriteifunchanged   Pass YES to this to skip output writing\n");
    printf("                          if a file already exists at -out with\n");
    printf("                          the same contents as would be written.");


    printf("\n\n");
}

#pragma mark - Main

int main(int argc, const char * argv[])
{

    @autoreleasepool {

        NSString *inputFilePath = [[NSUserDefaults standardUserDefaults] valueForKey:@"strings"];
        NSString *outputFilePath = [[NSUserDefaults standardUserDefaults] valueForKey:@"out"];
        BOOL skipWriteIfUnchanged = [[NSUserDefaults standardUserDefaults] boolForKey:@"skipwriteifunchanged"];
        NSFileManager *fileManager = [NSFileManager defaultManager];


        setbuf(stdout, NULL);

        if (inputFilePath.length == 0 || outputFilePath.length == 0) {
            printUsage();
            exit(EXIT_FAILURE);
        }

        if (![fileManager fileExistsAtPath:inputFilePath]) {
            printf("ERROR: Input file %s doesn't exist.\n", [inputFilePath UTF8String]);
            exit(EXIT_FAILURE);
        }

        NSError *error = nil;
        NSData *plistData = [NSData dataWithContentsOfFile:inputFilePath
                                                   options:0
                                                     error:&error];

        if (error != nil) {
            printf("ERROR: Reading input file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        id plist = [NSPropertyListSerialization propertyListWithData:plistData
                                                             options:0
                                                              format:nil
                                                               error:&error];

        if (error != nil) {
            printf("ERROR: Reading input file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        if (![plist isKindOfClass:[NSDictionary class]]) {
            printf("ERROR: Strings file contained unexpected root object type.");
            exit(EXIT_FAILURE);
        }

        NSMutableString *fileContents = [NSMutableString new];

        [fileContents appendFormat:@"// Generated by %@\n", [[NSProcessInfo processInfo] processName]];
        [fileContents appendFormat:@"// Source file: %@\n", inputFilePath];
        [fileContents appendString:@"// WARNING: This file was auto-generated. Do not modify by hand.\n\n"];

        [fileContents appendString:@"#import <Foundation/Foundation.h>\n\n"];

        NSCharacterSet *unsafeCharacters = [NSCharacterSet characterSetWithCharactersInString:@"."];

        for (NSString *key in plist) {
            NSString *safeKey = [[key componentsSeparatedByCharactersInSet:unsafeCharacters] componentsJoinedByString:@"_"];
            [fileContents appendString:[NSString stringWithFormat:@"static NSString * const %@ = @\"%@\";\n", safeKey, key]];
        }

        NSString *parentPath = [outputFilePath stringByDeletingLastPathComponent];
        if (![fileManager fileExistsAtPath:parentPath]) {
            if (![fileManager createDirectoryAtPath:parentPath
                        withIntermediateDirectories:YES
                                         attributes:nil
                                              error:&error]) {
                printf("ERROR: Creating parent directory failed with error: %s\n", error.localizedDescription.UTF8String);
                exit(EXIT_FAILURE);
            }
        }

        NSData *dataToWrite = [fileContents dataUsingEncoding:NSUTF8StringEncoding];

        if (skipWriteIfUnchanged && [fileManager fileExistsAtPath:outputFilePath]) {
            NSData *existingData = [NSData dataWithContentsOfFile:outputFilePath];

            if (existingData != nil && [dataToWrite isEqual:existingData]) {
                printf("File already exists at -out with the same contents as we'd write. Skipping.\n");
                exit(EXIT_SUCCESS);
            }
        }

        if (![dataToWrite writeToFile:outputFilePath options:NSDataWritingAtomic error:&error]) {
            printf("ERROR: Writing output file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        exit(EXIT_SUCCESS);

    }
    return 0;
}