//
//  main.m
//  generate-string-symbols
//
//  Created by Daniel Kennett on 07/08/14.
//  For license information, see LICENSE.markdown

#import <Foundation/Foundation.h>

#pragma mark - Usage

void printUsage() {

    NSString *processName = [[NSProcessInfo processInfo] processName];

    printf("%s by Daniel Kennett\n\n", processName.UTF8String);

    printf("Outputs a header file containing symbols for the give .strings\n");
    printf("file's keys.\n\n");

    printf("Usage: %s -out <output file path> \n", processName.UTF8String);
    printf("       %s -strings <strings file path>\n", [@"" stringByPaddingToLength:processName.length
                                                                         withString:@" "
                                                                    startingAtIndex:0].UTF8String);
    printf("\n\n");
}

#pragma mark - Main

int main(int argc, const char * argv[])
{

    @autoreleasepool {

        NSString *inputFilePath = [[NSUserDefaults standardUserDefaults] valueForKey:@"strings"];
        NSString *outputFilePath = [[NSUserDefaults standardUserDefaults] valueForKey:@"out"];

        setbuf(stdout, NULL);

        if (inputFilePath.length == 0 || outputFilePath.length == 0) {
            printUsage();
            exit(EXIT_FAILURE);
        }

        if (![[NSFileManager defaultManager] fileExistsAtPath:inputFilePath]) {
            printf("ERROR: Input file %s doesn't exist.\n", [inputFilePath UTF8String]);
            exit(EXIT_FAILURE);
        }

        NSError *error = nil;
        NSData *plistData = [NSData dataWithContentsOfFile:inputFilePath
                                                   options:0
                                                     error:&error];

        if (error != nil) {
            printf("ERROR: Reading input file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        id plist = [NSPropertyListSerialization propertyListWithData:plistData
                                                             options:0
                                                              format:nil
                                                               error:&error];

        if (error != nil) {
            printf("ERROR: Reading input file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        if (![plist isKindOfClass:[NSDictionary class]]) {
            printf("ERROR: Strings file contained unexpected root object type.");
            exit(EXIT_FAILURE);
        }

        NSMutableString *fileContents = [NSMutableString new];

        NSDateFormatter *formatter = [NSDateFormatter new];
        formatter.locale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"];
        formatter.dateFormat = @"yyyy-MM-dd HH:mm:ss ZZZZZ";

        [fileContents appendFormat:@"// Generated by %@ on %@\n", [[NSProcessInfo processInfo] processName], [formatter stringFromDate:[NSDate date]]];
        [fileContents appendFormat:@"// Source file: %@\n", inputFilePath];
        [fileContents appendString:@"// WARNING: This file was auto-generated. Do not modify by hand.\n\n"];

        [fileContents appendString:@"#import <Foundation/Foundation.h>\n\n"];

        for (NSString *key in plist) {
            [fileContents appendString:[NSString stringWithFormat:@"static NSString * const %@ = @\"%@\";\n", key, key]];
        }

        NSString *parentPath = [outputFilePath stringByDeletingLastPathComponent];
        if (![[NSFileManager defaultManager] fileExistsAtPath:parentPath]) {
            if (![[NSFileManager defaultManager] createDirectoryAtPath:parentPath
                                           withIntermediateDirectories:YES
                                                            attributes:nil
                                                                 error:&error]) {
                printf("ERROR: Creating parent directory failed with error: %s\n", error.localizedDescription.UTF8String);
                exit(EXIT_FAILURE);
            }
        }

        if (![fileContents writeToFile:outputFilePath atomically:YES encoding:NSUTF8StringEncoding error:&error]) {
            printf("ERROR: Writing output file failed with error: %s\n", error.localizedDescription.UTF8String);
            exit(EXIT_FAILURE);
        }

        exit(EXIT_SUCCESS);

    }
    return 0;
}